name: Send Telegram Message

on:
  schedule:
    - cron: '51 12 * * *' # Executa todos os dias às 10:30 AM UTC

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script to send Telegram message
        run: node index.js
